# Generated by Django 5.1.4 on 2025-01-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0002_producto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(null=True, upload_to='files/imagenes'),
        ),
    ]
